# Generated by Django 5.2.6 on 2025-09-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('cod_persona', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_persona', models.CharField(max_length=50)),
                ('ape_persona', models.CharField(max_length=50)),
                ('fec_nac', models.DateField()),
            ],
        ),
    ]
